In [232]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.datasets import imdb

max_features = 20000
# cut texts after this number of words (among top max_features most common words)
maxlen = 80
batch_size = 32

print('Loading data...')
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')

Loading data...
25000 train sequences
25000 test sequences


In [233]:
y_train.shape

(25000,)

In [234]:
print('Pad sequences (samples x time)')
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)

Pad sequences (samples x time)
x_train shape: (25000, 80)
x_test shape: (25000, 80)


In [235]:
# print('Build model...')
# model = Sequential()
# model.add(Embedding(max_features, 128, name = "main_input"))
# model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2,name='lstm_output'))
# model.add(Dense(1, activation='sigmoid'))

In [236]:
# from keras.layers import Input, Embedding, LSTM, Dense, merge
# from keras.models import Model

# # headline input: meant to receive sequences of 100 integers, between 1 and 10000.
# # note that we can name any layer by passing it a "name" argument.
# main_input = Input(shape=(80,), dtype='int32', name='main_input')
# print (main_input)
# # this embedding layer will encode the input sequence
# # into a sequence of dense 512-dimensional vectors.
# x = Embedding(output_dim=128, input_dim=20000, input_length=80)(main_input)
# print (x)
# # a LSTM will transform the vector sequence into a single vector,
# # containing information about the entire sequence
# lstm_out = LSTM(32,return_sequences = True)(x)
# print (lstm_out)

# auxiliary_loss = Dense(1, activation='sigmoid', name='aux_output')(lstm_out)
# print (auxiliary_loss)

# # auxiliary_input = Input(shape=(5,), name='aux_input')
# # x = merge([lstm_out, auxiliary_input], mode='concat')

# # we stack a deep fully-connected network on top
# x = Dense(64, activation='relu', name="dense_one")(x) # names are added here
# x = Dense(64, activation='relu', name="dense_two")(x)
# x = Dense(64, activation='relu', name="dense_three")(x)
# print (x)

# # and finally we add the main logistic regression layer
# main_loss = Dense(1, activation='sigmoid', name='main_output')(x)
# print (main_loss)

# model = Model(input=[main_input], output=[main_loss])
# model.compile(optimizer='adam', loss='binary_crossentropy',
#               loss_weights=[1.])
# #model.get_layer("dense_one")

In [239]:
# # try using different optimizers and different optimizer configs
# model.compile(loss='binary_crossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])

# print('Train...')
# model.fit(x_train, y_train,
#           batch_size=batch_size,
#           epochs=1,
#           validation_data=(x_test, y_test)
#          )

In [253]:
x_train = np.load("x_train.npy")
y_train = np.load("y_train.npy")

In [250]:
import keras
from keras.layers import Input, Embedding, LSTM, Dense
from keras.models import Model
import numpy as np
np.random.seed(0)  # Set a random seed for reproducibility

# Headline input: meant to receive sequences of 100 integers, between 1 and 10000.
# Note that we can name any layer by passing it a "name" argument.
main_input = Input(shape=(100,), dtype='int32', name='main_input')
main_input_2 = Input(shape=(100,), dtype='int32', name='main_input_2')

# This embedding layer will encode the input sequence
# into a sequence of dense 512-dimensional vectors.
x = Embedding(output_dim=512, input_dim=10000, input_length=100)(main_input)
x2 = Embedding(output_dim=10, input_dim=2, input_length=100)(main_input_2)
print ("x",x)
print ("x2",x2)
# A LSTM will transform the vector sequence into a single vector,
# containing information about the entire sequence
lstm_out,state_h,state_c = LSTM(32, name = "lstm_out", return_sequences = True, return_state = True)(x)
#lstm_out_feature = LSTM(32, name = "lstm_out_feature", return_sequences = True)(x)
print (lstm_out)
#auxiliary_output = Dense(1, activation='sigmoid', name='aux_output')(lstm_out)

#auxiliary_input = Input(shape=(5,), name='aux_input')
#x = keras.layers.concatenate([lstm_out, auxiliary_input])
#print (x)
# We stack a deep densely-connected network on top
x = Dense(64, activation='relu',name="dense_one")(state_h)
x = Dense(64, activation='relu',name="dense_two")(x)
x = Dense(64, activation='relu',name="dense_three")(x)

# And finally we add the main logistic regression layer
main_output = Dense(1, activation='sigmoid', name='main_output')(x)
model = Model(inputs=[main_input], outputs=[main_output])
model.compile(optimizer='rmsprop', 
              loss='binary_crossentropy',
              metrics=['accuracy'],
              loss_weights=None)

x Tensor("embedding_70/embedding_lookup/Identity:0", shape=(?, 100, 512), dtype=float32)
x2 Tensor("embedding_71/embedding_lookup/Identity:0", shape=(?, 100, 10), dtype=float32)
Tensor("lstm_out_40/transpose_1:0", shape=(?, ?, 32), dtype=float32)


In [251]:
headline_data = np.round(np.abs(np.random.rand(12, 100) * 100))
headline_data_1 = np.round(np.abs(np.random.rand(12, 100) * 2))

#additional_data = np.random.randn(12, 5)
headline_labels = np.random.randn(12, 1)
#additional_labels = np.random.randn(12, 1)


In [242]:
headline_data.shape

(12, 100)

In [245]:
headline_data_1[0]

array([0., 0., 1., 2., 1., 2., 1., 0., 1., 0., 0., 1., 1., 2., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 2., 1., 1., 0., 2., 1., 1., 0.,
       0., 0., 2., 2., 1., 2., 0., 1., 0., 2., 1., 0., 1., 1., 2., 0., 1.,
       2., 0., 1., 0., 2., 1., 2., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 2., 0., 1., 0., 1., 0., 0., 1., 2., 0., 2., 1., 1., 2., 1.,
       0., 0., 0., 2., 1., 1., 2., 0., 1., 1., 1., 1., 1., 0., 1.])

In [252]:
# model.fit([headline_data, additional_data], [headline_labels, additional_labels, ],
#           epochs=5, batch_size=32)
# And trained it via:
model.fit({'main_input': headline_data, 
           'main_input_2': headline_data_1,
          },
          {'main_output': headline_labels, 
           #'aux_output': additional_labels
          },
          epochs=50, batch_size=32)

Epoch 1/50
12/12 [==============================] - 6s 526ms/step - loss: 0.6936 - acc: 0.0000e+00
Epoch 2/50
12/12 [==============================] - 0s 11ms/step - loss: 0.6498 - acc: 0.0000e+00
Epoch 3/50
12/12 [==============================] - 0s 12ms/step - loss: 0.5720 - acc: 0.0000e+00
Epoch 4/50
12/12 [==============================] - 0s 11ms/step - loss: 0.4471 - acc: 0.0000e+00
Epoch 5/50
12/12 [==============================] - 0s 11ms/step - loss: 0.2358 - acc: 0.0000e+00
Epoch 6/50
12/12 [==============================] - 0s 11ms/step - loss: -0.1124 - acc: 0.0000e+00
Epoch 7/50
12/12 [==============================] - 0s 11ms/step - loss: -0.6465 - acc: 0.0000e+00
Epoch 8/50
12/12 [==============================] - 0s 12ms/step - loss: -1.3919 - acc: 0.0000e+00
Epoch 9/50
12/12 [==============================] - 0s 11ms/step - loss: -2.2623 - acc: 0.0000e+00
Epoch 10/50
12/12 [==============================] - 0s 11ms/step - loss: -3.3189 - acc: 0.0000e+00
Epoch 11/50
1

In [145]:
main_output, auxiliary_output = model.predict({'main_input': headline_data, 'aux_input': additional_data})


In [146]:
main_output.shape

(12, 1)

In [147]:
auxiliary_output.shape

(12, 1)

In [148]:
main_output

array([[0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [2.9802322e-08],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [7.7507401e-01],
       [9.9517137e-01],
       [0.0000000e+00],
       [2.4931315e-01]], dtype=float32)

In [149]:
auxiliary_output

array([[3.3938566e-01],
       [1.1312962e-03],
       [8.3271861e-03],
       [7.5623226e-01],
       [3.3980608e-04],
       [2.4066001e-01],
       [4.6593377e-01],
       [1.4150143e-04],
       [4.9779296e-01],
       [2.7680397e-04],
       [4.0855616e-01],
       [3.7595630e-04]], dtype=float32)

In [155]:
model.get_layer("lstm_out").output

[<tf.Tensor 'main_input_38:0' shape=(?, 100) dtype=int32>,
 <tf.Tensor 'aux_input_18:0' shape=(?, 5) dtype=float32>]

In [227]:
new_model = Model(model.inputs, model.get_layer("lstm_out").output)

In [228]:
lstm_out, state_h, state_c = new_model.predict({'main_input': headline_data})

In [229]:
lstm_out.shape

(12, 100, 32)

In [230]:
state_h.shape

(12, 32)

In [231]:
state_c.shape

(12, 32)

In [226]:
new_model = Model(model.inputs, model.get_layer("dense_three").output)
hidden_out = new_model.predict({'main_input': headline_data})

In [205]:
hidden_out.shape

(12, 64)

In [206]:
new_model = Model(model.inputs, model.get_layer("main_output").output)
prediction = new_model.predict({'main_input': headline_data})
prediction.shape

(12, 1)

In [207]:
prediction

array([[5.9604645e-08],
       [0.0000000e+00],
       [1.0494286e-01],
       [0.0000000e+00],
       [9.9839771e-01],
       [0.0000000e+00],
       [0.0000000e+00],
       [6.6406488e-01],
       [2.9802322e-08],
       [0.0000000e+00],
       [8.9902139e-01],
       [0.0000000e+00]], dtype=float32)

In [200]:
# reference:https://github.com/keras-team/keras/issues/2766